-- MySQL Script generated by MySQL Workbench
-- Sat Mar 25 11:40:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema controlestoque
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema controlestoque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controlestoque` DEFAULT CHARACTER SET utf8mb4 ;
USE `controlestoque` ;

-- -----------------------------------------------------
-- Table `controlestoque`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlestoque`.`Usuario` (
  `Iduser` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(75) NOT NULL,
  `Email` VARCHAR(75) NOT NULL,
  `Password` VARCHAR(75) NOT NULL,
  `Dataregistro` DATE NOT NULL,
  `Permissao` INT NOT NULL,
  PRIMARY KEY (`Iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlestoque`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlestoque`.`Produto` (
  `CodRefProduto` INT NOT NULL AUTO_INCREMENT,
  `NomeProduto` VARCHAR(75) NULL,
  `Usuario_Iduser` INT NOT NULL,
  PRIMARY KEY (`CodRefProduto`),
  INDEX `fk_Produto_Usuario1_idx` (`Usuario_Iduser` ASC),
  CONSTRAINT `fk_Produto_Usuario1`
    FOREIGN KEY (`Usuario_Iduser`)
    REFERENCES `controlestoque`.`Usuario` (`Iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlestoque`.`Fabricante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlestoque`.`Fabricante` (
  `IdFabricante` INT NOT NULL AUTO_INCREMENT,
  `NomeFabricante` VARCHAR(75) NOT NULL,
  `CNPJFabricante` VARCHAR(75) NOT NULL,
  `EmailFabricante` VARCHAR(75) NOT NULL,
  `EnderecoFabricante` VARCHAR(75) NOT NULL,
  `TelefoneFabricante` VARCHAR(16) NOT NULL,
  `Usuario_Iduser` INT NOT NULL,
  PRIMARY KEY (`IdFabricante`),
  INDEX `fk_Fabricante_Usuario1_idx` (`Usuario_Iduser` ASC),
  CONSTRAINT `fk_Fabricante_Usuario1`
    FOREIGN KEY (`Usuario_Iduser`)
    REFERENCES `controlestoque`.`Usuario` (`Iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlestoque`.`Representante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlestoque`.`Representante` (
  `idRepresentante` INT NOT NULL AUTO_INCREMENT,
  `NomeRepresentante` VARCHAR(75) NOT NULL,
  `TelefoneRepresentante` VARCHAR(16) NOT NULL,
  `EmailRepresentante` VARCHAR(75) NOT NULL,
  `Fabricante_IdFabricante` INT NOT NULL,
  `Usuario_Iduser` INT NOT NULL,
  PRIMARY KEY (`idRepresentante`),
  INDEX `fk_Representante_Fabricante1_idx` (`Fabricante_IdFabricante` ASC),
  INDEX `fk_Representante_Usuario1_idx` (`Usuario_Iduser` ASC),
  CONSTRAINT `fk_Representante_Fabricante1`
    FOREIGN KEY (`Fabricante_IdFabricante`)
    REFERENCES `controlestoque`.`Fabricante` (`IdFabricante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Representante_Usuario1`
    FOREIGN KEY (`Usuario_Iduser`)
    REFERENCES `controlestoque`.`Usuario` (`Iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlestoque`.`Itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlestoque`.`Itens` (
  `idItens` INT NOT NULL AUTO_INCREMENT,
  `QuantItens` INT NOT NULL,
  `QuantItensVend` INT NOT NULL,
  `ValCompItens` FLOAT NOT NULL,
  `ValVendItens` FLOAT NOT NULL,
  `DataCompraItens` DATE NOT NULL,
  `DataVenci_Itens` DATE NOT NULL,
  `Ativo` INT NOT NULL,
  `Produto_CodRefProduto` INT NOT NULL,
  `Fabricante_IdFabricante` INT NOT NULL,
  `Usuario_Iduser` INT NOT NULL,
  PRIMARY KEY (`idItens`),
  INDEX `fk_Itens_Produto_idx` (`Produto_CodRefProduto` ASC),
  INDEX `fk_Itens_Fabricante1_idx` (`Fabricante_IdFabricante` ASC),
  INDEX `fk_Itens_Usuario1_idx` (`Usuario_Iduser` ASC),
  CONSTRAINT `fk_Itens_Produto`
    FOREIGN KEY (`Produto_CodRefProduto`)
    REFERENCES `controlestoque`.`Produto` (`CodRefProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Itens_Fabricante1`
    FOREIGN KEY (`Fabricante_IdFabricante`)
    REFERENCES `controlestoque`.`Fabricante` (`IdFabricante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Itens_Usuario1`
    FOREIGN KEY (`Usuario_Iduser`)
    REFERENCES `controlestoque`.`Usuario` (`Iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
